# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "wheelysvc.Point" do
    optional :lat, :double, 1
    optional :lng, :double, 2
  end
  add_message "wheelysvc.Ride" do
    optional :origin, :message, 1, "wheelysvc.Point"
    optional :destination, :message, 2, "wheelysvc.Point"
  end
  add_message "wheelysvc.DirectionResult" do
    optional :distance, :int64, 1
    optional :duration, :int64, 2
  end
end

module Wheelysvc
  Point = Google::Protobuf::DescriptorPool.generated_pool.lookup("wheelysvc.Point").msgclass
  Ride = Google::Protobuf::DescriptorPool.generated_pool.lookup("wheelysvc.Ride").msgclass
  DirectionResult = Google::Protobuf::DescriptorPool.generated_pool.lookup("wheelysvc.DirectionResult").msgclass
end
