# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: service.proto for package 'wheelysvc'

require 'grpc'
require 'service_pb'

module Wheelysvc
  module DistanceCalcultaion
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'wheelysvc.DistanceCalcultaion'

      rpc :Calculate, Ride, DirectionResult
    end

    Stub = Service.rpc_stub_class
  end
end
