// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package wheelysvc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Point) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

type Ride struct {
	Origin               *Point   `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          *Point   `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ride) Reset()         { *m = Ride{} }
func (m *Ride) String() string { return proto.CompactTextString(m) }
func (*Ride) ProtoMessage()    {}
func (*Ride) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}
func (m *Ride) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ride.Unmarshal(m, b)
}
func (m *Ride) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ride.Marshal(b, m, deterministic)
}
func (m *Ride) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ride.Merge(m, src)
}
func (m *Ride) XXX_Size() int {
	return xxx_messageInfo_Ride.Size(m)
}
func (m *Ride) XXX_DiscardUnknown() {
	xxx_messageInfo_Ride.DiscardUnknown(m)
}

var xxx_messageInfo_Ride proto.InternalMessageInfo

func (m *Ride) GetOrigin() *Point {
	if m != nil {
		return m.Origin
	}
	return nil
}

func (m *Ride) GetDestination() *Point {
	if m != nil {
		return m.Destination
	}
	return nil
}

type DirectionResult struct {
	Distance             int64    `protobuf:"varint,1,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration             int64    `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DirectionResult) Reset()         { *m = DirectionResult{} }
func (m *DirectionResult) String() string { return proto.CompactTextString(m) }
func (*DirectionResult) ProtoMessage()    {}
func (*DirectionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}
func (m *DirectionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DirectionResult.Unmarshal(m, b)
}
func (m *DirectionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DirectionResult.Marshal(b, m, deterministic)
}
func (m *DirectionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DirectionResult.Merge(m, src)
}
func (m *DirectionResult) XXX_Size() int {
	return xxx_messageInfo_DirectionResult.Size(m)
}
func (m *DirectionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DirectionResult.DiscardUnknown(m)
}

var xxx_messageInfo_DirectionResult proto.InternalMessageInfo

func (m *DirectionResult) GetDistance() int64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *DirectionResult) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "wheelysvc.Point")
	proto.RegisterType((*Ride)(nil), "wheelysvc.Ride")
	proto.RegisterType((*DirectionResult)(nil), "wheelysvc.DirectionResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DistanceCalcultaionClient is the client API for DistanceCalcultaion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DistanceCalcultaionClient interface {
	Calculate(ctx context.Context, in *Ride, opts ...grpc.CallOption) (*DirectionResult, error)
}

type distanceCalcultaionClient struct {
	cc *grpc.ClientConn
}

func NewDistanceCalcultaionClient(cc *grpc.ClientConn) DistanceCalcultaionClient {
	return &distanceCalcultaionClient{cc}
}

func (c *distanceCalcultaionClient) Calculate(ctx context.Context, in *Ride, opts ...grpc.CallOption) (*DirectionResult, error) {
	out := new(DirectionResult)
	err := c.cc.Invoke(ctx, "/wheelysvc.DistanceCalcultaion/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DistanceCalcultaionServer is the server API for DistanceCalcultaion service.
type DistanceCalcultaionServer interface {
	Calculate(context.Context, *Ride) (*DirectionResult, error)
}

func RegisterDistanceCalcultaionServer(s *grpc.Server, srv DistanceCalcultaionServer) {
	s.RegisterService(&_DistanceCalcultaion_serviceDesc, srv)
}

func _DistanceCalcultaion_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ride)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DistanceCalcultaionServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wheelysvc.DistanceCalcultaion/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DistanceCalcultaionServer).Calculate(ctx, req.(*Ride))
	}
	return interceptor(ctx, in, info, handler)
}

var _DistanceCalcultaion_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wheelysvc.DistanceCalcultaion",
	HandlerType: (*DistanceCalcultaionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _DistanceCalcultaion_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0x03, 0x31,
	0x10, 0xc6, 0x59, 0xab, 0xc5, 0x4e, 0x91, 0x96, 0x78, 0x29, 0x7b, 0x92, 0x3d, 0x15, 0x84, 0x3d,
	0xac, 0x17, 0xef, 0xf6, 0xe2, 0x49, 0xc9, 0x1b, 0xc4, 0x64, 0x58, 0x07, 0xc2, 0x44, 0x92, 0xd9,
	0x8a, 0x6f, 0x2f, 0x89, 0x61, 0x5d, 0xc4, 0x5b, 0xbe, 0x3f, 0xfc, 0xf2, 0x25, 0x70, 0x93, 0x30,
	0x9e, 0xc9, 0x62, 0xff, 0x11, 0x83, 0x04, 0xb5, 0xf9, 0x7c, 0x47, 0xf4, 0x5f, 0xe9, 0x6c, 0xbb,
	0x7b, 0xb8, 0x7a, 0x0d, 0xc4, 0xa2, 0xf6, 0xb0, 0xf2, 0x46, 0x0e, 0xcd, 0x5d, 0x73, 0x6c, 0x74,
	0x3e, 0x16, 0x87, 0xc7, 0xc3, 0x45, 0x75, 0x78, 0xec, 0x1c, 0x5c, 0x6a, 0x72, 0xa8, 0x8e, 0xb0,
	0x0e, 0x91, 0x46, 0xe2, 0x52, 0xdf, 0x0e, 0xfb, 0x7e, 0x06, 0xf6, 0x85, 0xa6, 0x6b, 0xae, 0x06,
	0xd8, 0x3a, 0x4c, 0x42, 0x6c, 0x84, 0x02, 0x17, 0xd6, 0x7f, 0xf5, 0x65, 0xa9, 0x7b, 0x86, 0xdd,
	0x89, 0x22, 0xda, 0x2c, 0x34, 0xa6, 0xc9, 0x8b, 0x6a, 0xe1, 0xda, 0x51, 0x12, 0xc3, 0x16, 0xcb,
	0x95, 0x2b, 0x3d, 0xeb, 0x92, 0x4d, 0xf1, 0x97, 0x9f, 0xb3, 0xaa, 0x87, 0x17, 0xb8, 0x3d, 0xd5,
	0xde, 0x93, 0xf1, 0x76, 0xf2, 0x62, 0x28, 0xb0, 0x7a, 0x84, 0xcd, 0x8f, 0x34, 0x82, 0x6a, 0xb7,
	0x58, 0x93, 0x5f, 0xd7, 0xb6, 0x0b, 0xe3, 0xcf, 0x90, 0xb7, 0x75, 0xf9, 0xc0, 0x87, 0xef, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe3, 0x86, 0x8b, 0x77, 0x51, 0x01, 0x00, 0x00,
}
